name: Build JIT Plugin

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:20.04  # O la versi√≥n que necesites
    
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y git build-essential cmake gcc-multilib g++-multilib
      
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Build plugin
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-m32 -DCMAKE_C_FLAGS=-m32
          make
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: jit-plugin
          path: build/*.so
