name: Compilar Plugin JIT Linux
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del c√≥digo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Instalar herramientas de 32 bits
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib g++-multilib cmake

      - name: Configurar y Compilar
        run: |
          rm -rf build_linux
          mkdir build_linux
          cd build_linux
          cmake -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32 ..
          make

      - name: Listar archivos generados (Debug)
        run: find build_linux -name "*.so"

      - name: Guardar archivo .so
        uses: actions/upload-artifact@v4
        with:
          name: jit-linux-so
          path: build_linux/**/*.so
